version: "3.8"

services:
  ahmed-portfolio-frontend:
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - "5001" # Expose port only for the first instance
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ahmed-portfolio-frontend.rule=Host(`ahmed-portfolio.genydev.com`)"
      - "traefik.http.routers.ahmed-portfolio-frontend.entrypoints=websecure"
      - "traefik.http.routers.ahmed-portfolio-frontend.tls=true"
      - "traefik.http.routers.ahmed-portfolio-frontend.tls.certresolver=le"
      - "traefik.http.routers.ahmed-portfolio-frontend.tls.domains[0].main=ahmed-portfolio.genydev.com"
      - "traefik.http.middlewares.ahmed-portfolio-frontend-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.ahmed-portfolio-frontend.middlewares=ahmed-portfolio-frontend-redirect"
    volumes:
      - "~/shared_vps/traefik/certs:/letsencrypt" # Ensure correct path and permissions for volumes
    networks:
      - traefikNetwork
      - ahmed-portfolioNet
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  traefikNetwork:
    external: true
  ahmed-portfolioNet:
    driver: bridge
    internal: true
